services:
  postgres:
    image: postgres
    container_name: ${POSTGRES_DB}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 54320:${POSTGRES_PORT}
    restart: always
    volumes:
      - /db:/var/lib/postgresql/data