services:
  postgres:
    image: postgres
    container_name: ${POSTGRES_DB}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 54320:${POSTGRES_PORT}
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    
  backend:
    image: backend
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: backend
    ports:
      - 8001:8000
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - postgres
    restart: always